#!/usr/bin/env bash

echo "Making a copy to edit."
cp snake_bounce.py snake_bounce.py.template

if [ -z "$1"  ]; then
  echo "Enter your server name."
  read servername
else
  server="$1"
fi

echo "Using $servername as server name"
sed -i "s/YOURSERVERGOESHERE/$servername/g" snake_bounce.py.template
echo "Making program to run as sb.py"
mv snake_bounce.py.template sb.py
echo "Running snake bounce as sb.py now"

python sb.py || python3 sb.py || python27 sb.py
